#!/usr/bin/env python
# Author: Allen Liu
# Software License Agreement (BSD License)
# Copyright (c) 2017-2018, Aubo Robotics
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the name of SRI International nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
## To use the python interface to move_group, import the moveit_commander
## module.  We also import rospy and some messages that we will use.
import sys
import copy
import rospy
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg

from std_msgs.msg import String

def move_group_python_interface():

  moveit_commander.roscpp_initialize(sys.argv)
  rospy.init_node('move_group_python_interface', anonymous=True)

  robot = moveit_commander.RobotCommander()


  scene = moveit_commander.PlanningSceneInterface()

  group = moveit_commander.MoveGroupCommander("move_arm")


  ## We create this DisplayTrajectory publisher which is used below to publish
  ## trajectories for RVIZ to visualize.
  display_trajectory_publisher = rospy.Publisher(
                                      '/move_group/display_planned_path',
                                      moveit_msgs.msg.DisplayTrajectory)

  print "============ Waiting for RVIZ..."
  rospy.sleep(1)


  ## We can get the name of the reference frame for this robot
  print "============ Reference frame: %s" % group.get_planning_frame()

  ## We can also print the name of the end-effector link for this group
  print "============ Reference frame: %s" % group.get_end_effector_link()

  ## We can get a list of all the groups in the robot
  print "============ Robot Groups:"
  print robot.get_group_names()

  ## Sometimes for debugging it is useful to print the entire state of the
  ## robot.
  print "============ Printing robot state"
  print robot.get_current_state()
  print "============"


  ## Moving to a pose goal
  while not rospy.is_shutdown():
    a = 1
    if(a == 1):
      a = 2
      group.clear_pose_targets()
      ## Then, we will get the current set of joint values for the group
      group_variable_values = group.get_current_joint_values()
      print "============ Joint values: ", group_variable_values
      ## Now, let's modify one of the joints, plan to the new joint
      ## space goal and visualize the plan
      group_variable_values[0] = -0.5
      group_variable_values[1] = 2.045322
      group_variable_values[2] = 0.544908
      group_variable_values[3] = -1.884432
      group_variable_values[4] = 0.749672
      group_variable_values[5] = 1.410019
      group_variable_values[6] = 0.0
      group.set_joint_value_target(group_variable_values)

      plan1 = group.plan()
      group.go(wait=True)
      rospy.sleep(1)

      group.clear_pose_targets()
      ## Then, we will get the current set of joint values for the group
      group_variable_values = group.get_current_joint_values()
      print "============ Joint values: ", group_variable_values
      ## Now, let's modify one of the joints, plan to the new joint
      ## space goal and visualize the plan
      group_variable_values[0] = 0.5
      group_variable_values[1] = 2.045322
      group_variable_values[2] = 0.544908
      group_variable_values[3] = -1.884432
      group_variable_values[4] = 0.749672
      group_variable_values[5] = 1.410019
      group_variable_values[6] = 0.0
      group.set_joint_value_target(group_variable_values)

      plan2 = group.plan()
      group.go(wait=True)
      rospy.sleep(1)


  ## When finished shut down moveit_commander.
  moveit_commander.roscpp_shutdown()


if __name__=='__main__':
  try:
    move_group_python_interface()
  except rospy.ROSInterruptException:
    pass

